# Generated by Django 2.2.3 on 2019-08-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagecarouselimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
    ]
