# Generated by Django 2.2.4 on 2019-08-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190829_0443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageCarouselImages',
        ),
    ]
