# Generated by Django 2.2.3 on 2019-07-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='instragram',
            new_name='instagram',
        ),
    ]
